import assets from "@/assets/images/assets";
import { Product } from "@/types/product.t";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "001",
    title: "Wireless Earbuds, IPX8",
    category: "Électronique",
    price: "98 900 Ar",
    oldPrice: "120 000 Ar",
    image: assets.electronicsCategory,
    href: "/products/001",
    rating: 4.6,
    reviewsCount: 213,
  },
  {
    id: "002",
    title: "AirPods Max Premium",
    category: "Électronique",
    price: "559 900 Ar",
    oldPrice: "699 900 Ar",
    image: assets.heroIllus2,
    href: "/products/002",
    rating: 4.8,
    reviewsCount: 412,
  },
  {
    id: "003",
    title: "BOSE BT Earphones",
    category: "Électronique",
    price: "289 900 Ar",
    oldPrice: "350 000 Ar",
    image: assets.heroIllus3,
    href: "/products/003",
    rating: 4.4,
    reviewsCount: 178,
  },
  {
    id: "004",
    title: "JBL Tune 600BTNC",
    category: "Électronique",
    price: "199 900 Ar",
    oldPrice: "249 900 Ar",
    image: assets.heroIllus1,
    href: "/products/004",
    rating: 4.3,
    reviewsCount: 95,
  },
  {
    id: "005",
    title: "TAGRY Bluetooth Headset",
    category: "Électronique",
    price: "109 900 Ar",
    oldPrice: "139 900 Ar",
    image: assets.electronicsCategory,
    href: "/products/005",
    rating: 4.2,
    reviewsCount: 268,
  },
  {
    id: "006",
    title: "Monster MNFLEX Sport",
    category: "Électronique",
    price: "189 900 Ar",
    oldPrice: "229 900 Ar",
    image: assets.heroIllus3,
    href: "/products/006",
    rating: 4.1,
    reviewsCount: 73,
  },
  {
    id: "007",
    title: "Robe d'été élégante",
    category: "Mode Femme",
    price: "45 900 Ar",
    oldPrice: "65 000 Ar",
    image: assets.clothesCategory,
    href: "/products/007",
    rating: 4.7,
    reviewsCount: 189,
  },
  {
    id: "008",
    title: "Sneakers Sport Confort",
    category: "Chaussures",
    price: "79 900 Ar",
    oldPrice: "99 900 Ar",
    image: assets.shoesCategory,
    href: "/products/008",
    rating: 4.5,
    reviewsCount: 302,
  },
  {
    id: "009",
    title: "Sac à main cuir",
    category: "Accessoires",
    price: "129 900 Ar",
    oldPrice: "169 900 Ar",
    image: assets.accessoriesCategory,
    href: "/products/009",
    rating: 4.6,
    reviewsCount: 156,
  },
  {
    id: "010",
    title: "Set de maquillage",
    category: "Beauté",
    price: "89 900 Ar",
    oldPrice: "119 900 Ar",
    image: assets.beautyCategory,
    href: "/products/010",
    rating: 4.4,
    reviewsCount: 234,
  },
  {
    id: "011",
    title: "Coussin décoratif",
    category: "Maison",
    price: "29 900 Ar",
    oldPrice: "39 900 Ar",
    image: assets.houseCategory,
    href: "/products/011",
    rating: 4.3,
    reviewsCount: 98,
  },
  {
    id: "012",
    title: "T-shirt basique premium",
    category: "Mode Homme",
    price: "35 900 Ar",
    oldPrice: "49 900 Ar",
    image: assets.clothesCategory,
    href: "/products/012",
    rating: 4.5,
    reviewsCount: 421,
  },
  {
    id: "013",
    title: "Casquette streetwear",
    category: "Accessoires",
    price: "25 900 Ar",
    oldPrice: "35 900 Ar",
    image: assets.accessoriesCategory,
    href: "/products/013",
    rating: 4.2,
    reviewsCount: 87,
  },
  {
    id: "014",
    title: "Montre connectée Sport",
    category: "Électronique",
    price: "349 900 Ar",
    oldPrice: "449 900 Ar",
    image: assets.electronicsCategory,
    href: "/products/014",
    rating: 4.7,
    reviewsCount: 543,
  },
  {
    id: "015",
    title: "Jean slim fit",
    category: "Mode Homme",
    price: "89 900 Ar",
    oldPrice: "119 900 Ar",
    image: assets.clothesCategory,
    href: "/products/015",
    rating: 4.4,
    reviewsCount: 267,
  },
  {
    id: "016",
    title: "Parfum Floral 50ml",
    category: "Beauté",
    price: "159 900 Ar",
    oldPrice: "199 900 Ar",
    image: assets.beautyCategory,
    href: "/products/016",
    rating: 4.6,
    reviewsCount: 321,
  },
  {
    id: "017",
    title: "Lampe de bureau LED",
    category: "Maison",
    price: "49 900 Ar",
    oldPrice: "69 900 Ar",
    image: assets.houseCategory,
    href: "/products/017",
    rating: 4.3,
    reviewsCount: 145,
  },
  {
    id: "018",
    title: "Baskets running",
    category: "Chaussures",
    price: "129 900 Ar",
    oldPrice: "179 900 Ar",
    image: assets.shoesCategory,
    href: "/products/018",
    rating: 4.8,
    reviewsCount: 612,
  },
  {
    id: "019",
    title: "Robe cocktail élégante",
    category: "Mode Femme",
    price: "99 900 Ar",
    oldPrice: "149 900 Ar",
    image: assets.clothesCategory,
    href: "/products/019",
    rating: 4.5,
    reviewsCount: 234,
  },
  {
    id: "020",
    title: "Lunettes de soleil",
    category: "Accessoires",
    price: "79 900 Ar",
    oldPrice: "99 900 Ar",
    image: assets.accessoriesCategory,
    href: "/products/020",
    rating: 4.4,
    reviewsCount: 198,
  },
];

export default MOCK_PRODUCTS;

