import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const clashGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/ClashGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../../public/fonts/ClashGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],

  variable: "--font-clash-grotesk",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashGrotesk.variable} antialiased`}>{children}</body>
    </html>
  );
}
